name: Test and Deploy

# Workflow가 실행될 조건
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

# 실행할 작업들
jobs:
  # 테스트 작업
  test:
    runs-on: ubuntu-latest

    steps:
      # 1단계: 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2단계: Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 3단계: 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4단계: 린트 검사
      - name: Run linting
        run: npm run lint

      # 5단계: 테스트 실행
      - name: Run tests
        run: npm run test

      # 6단계: 테스트 커버리지 실행
      - name: Run test coverage
        run: npm run test:coverage

      # 7단계: 빌드 테스트
      - name: Build application
        run: npm run build

  deploy:
    # needs: test # test 작업이 성공해야 실행
    runs-on: ubuntu-latest

    steps:
      # 1단계: 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2단계: Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 3단계: 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4단계: 프로덕션 빌드
      - name: Build for production
        run: npm run build

      # 5단계: 배포 시뮬레이션
      - name: Simulate deployment
        run: echo "🚀 Simulating deployment to production..."
