name: Frontend Developer Context Examples
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Essential Context Info
        run: |
          echo "=== 프론트엔드 개발자를 위한 Context 정보 ==="
          echo ""
          echo "1. 저장소 정보"
          echo "   저장소: ${{ github.repository }}"
          echo "   소유자: ${{ github.repository_owner }}"
          echo ""
          echo "2. 브랜치 정보"
          echo "   현재 브랜치: ${{ github.ref_name }}"
          echo "   전체 참조: ${{ github.ref }}"
          echo ""
          echo "3. 커밋 정보"
          echo "   커밋 해시: ${{ github.sha }}"
          echo "   커밋 메시지: ${{ github.event.head_commit.message }}"
          echo ""
          echo "4. 이벤트 정보"
          echo "   이벤트 타입: ${{ github.event_name }}"
          echo "   실행자: ${{ github.actor }}"
          echo ""
          echo "5. 워크플로우 정보"
          echo "   워크플로우 이름: ${{ github.workflow }}"
          echo "   실행 번호: ${{ github.run_number }}"
          echo ""
          echo "6. 실행 환경"
          echo "   운영체제: ${{ runner.os }}"
          echo "   워크스페이스: ${{ runner.workspace }}"
          echo ""
          echo "7. 작업 상태"
          echo "   작업 상태: ${{ job.status }}"
          echo ""
          echo "8. 환경 변수"
          echo "   NODE_ENV: ${{ env.NODE_ENV }}"
          echo "   GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}"
          echo ""
          echo "9. Pull Request 정보 (PR인 경우)"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "   PR 번호: ${{ github.event.pull_request.number }}"
            echo "   PR 제목: ${{ github.event.pull_request.title }}"
            echo "   PR 작성자: ${{ github.event.pull_request.user.login }}"
          else
            echo "   PR 정보: 이번 실행은 PR이 아닙니다"
          fi
          echo ""
          echo "10. 이벤트 상세 정보"
          echo "    이벤트 파일 경로: ${{ github.event_path }}"
