name: basic workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 저장소 코드 다운로드
      - name: Checkout Code
        uses:actions/checkout@v4 # 저장소의 모든 파일을 가상머신으로 복사      

      # Step 2: Node.js 의존성 설치
      - name: install deps
        run: npm ci # package-lock.json을 기반으로 정확한 버전의 패키지 설치