name: basic workflow
on: push
jobs:
  # Job 1: 린트 검사 작업 (build와 병렬로 실행됨)
  lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 저장소 코드 다운로드
      - name: checkout code
        uses: actions/checkout@v4

      # Step 2: 의존성 설치
      - name: install dependencies
        run: npm ci

      # Step 3: 코드 품질 검사 실행
      - name: run lint
        run: npm run lint

  # Job 2: 빌드 작업
  build:
    runs-on: ubuntu-latest
    needs: lint # lint job이 성공적으로 완료된 후에만 실행
    steps:
      # Step 1: 저장소 코드 다운로드
      - name: checkout code
        uses: actions/checkout@v4 # 저장소의 모든 파일을 가상머신으로 복사

      # Step 2: 의존성 설치
      - name: install dependencies
        run: npm ci # package-lock.json을 기반으로 정확한 버전의 패키지 설치

      # Step 3: 프로덕션 빌드 실행
      - name: run build
        run: npm run build # package.json의 build 스크립트 실행
